### ISSUE TITLE
Installed but won't load

### ISSUE THREAD

**Issue by meldarionqeusse** [MichaelDavidHarry/joplin-armv7l#1]
I downloaded the .deb file and installed it. Joplin came up but I only have a blabk joplin page anything else I need to install?

**Comment by meldarionqeusse** [comment]
Installing version 2.1.8 worked not sure what changed in the latest version. I noticed docker file mentions bullseye I am still running buster not sure if that's got anything to do with it.

**Comment by MichaelDavidHarry** [comment]
Thank you for the feedback! I'll take a look at what is happening on Buster. I've only been testing it on Bullseye since I upgraded my RPi.

**Comment by MichaelDavidHarry** [comment]
@meldarionqeusse I did some testing on Buster and I found there was an issue happening with the releases that were built after the Dockerfile's base image was changed from Buster to Bullseye. I've reverted that change and rebuilt the v2.6.9 and v2.6.10 releases, and these builds appear to work on both Buster and Bullseye when I tested them.

Can you try the latest (v2.6.10) release on your Buster install and let me know if you're still having this problem?

Again, thank you for letting me know about this issue!

**Comment by meldarionqeusse** [comment]
Hi thank you very much for taking your time go fix the issue and putting forward version 10. Both 2.6.9 and 2.6.10 worked flawlessly. Thank you very much especially for solving it so quickly
